print("========================================================")
print("                 Personal Profile")
print("========================================================")

name = input("Enter your name: ")
age = input("Enter your age: ")
gender = input("Enter your gender: ")
city = input("Enter your city: ")
profession = input("Enter your profession: ")
course = input("Enter your course: ")
skills = input("Enter your skills: ")
career_goal = input("Enter your career goal: ")
hobby = input("Enter your hobby: ")
email = input("Enter your email: ")

print("========================================================")
print("                 Personal Profile")
print("========================================================")

print("Name         :", name)
print("Age          :", age)
print("Gender       :", gender)
print("City         :", city)
print("Profession   :", profession)
print("Course       :", course)
print("Skills       :", skills)
print("Career Goal  :", career_goal)
print("Hobby        :", hobby)
print("Email        :", email)

print("========================================================")
print("          Profile Generated Successfully")
print("========================================================")